"""
Database models for QuantLab metadata and results.

Supports both legacy on_bar and Prosperity trader.py strategies.
"""

import os
import uuid
from datetime import datetime
from typing import Generator
from sqlalchemy import create_engine, Column, String, Integer, Float, Text, DateTime, inspect, text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session

# Environment: Fallback to SQLite if DATABASE_URL not specified
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./quantlab.db")

# Setup engine
if DATABASE_URL.startswith("sqlite"):
    engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
else:
    engine = create_engine(DATABASE_URL)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class StrategyDB(Base):
    """Stores strategy code, symbols, interval, capital, and metadata."""
    __tablename__ = "strategies"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    name = Column(String, index=True, nullable=False)
    description = Column(Text, nullable=True)
    code = Column(Text, nullable=False)  # Full strategy source code

    # NEW: Strategy configuration (Prosperity-style)
    symbols = Column(Text, default='["SBIN"]')  # JSON array of symbols
    interval = Column(String, default="FIVE_MINUTE", nullable=False)
    initial_capital = Column(Float, default=100000.0, nullable=False)
    max_position_size = Column(Integer, nullable=True)
    parameters_json = Column(Text, nullable=True)  # JSON: strategy parameters
    risk_settings_json = Column(Text, nullable=True)  # JSON: risk settings

    # Runtime type and entrypoint
    runtime_type = Column(String, default="legacy_on_bar", nullable=False)  # "legacy_on_bar" or "prosperity_trader"
    entrypoint = Column(String, nullable=True)  # e.g., "trader.py:Trader" for Prosperity

    version = Column(Integer, default=1)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)



class DeploymentDB(Base):
    """Stores deployments of strategies (paper or live)."""
    __tablename__ = "deployments"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    strategy_id = Column(String, nullable=False, index=True)
    name = Column(String, nullable=False)
    symbol = Column(String, nullable=True)  # Specific symbol, or null for all strategy symbols
    mode = Column(String, default="paper", nullable=False)  # "paper" or "live"
    status = Column(String, default="active", nullable=False)  # "active", "paused", "stopped"
    config_json = Column(Text, nullable=True)  # Extra deployment-specific config
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class LiveTradeDB(Base):
    """Tracks every mock trade generated by a live deployment."""
    __tablename__ = "live_trades"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    deployment_id = Column(String, nullable=False, index=True)
    strategy_id = Column(String, nullable=False, index=True)
    symbol = Column(String, nullable=False)
    direction = Column(String, nullable=False)  # BUY or SELL
    price = Column(Float, nullable=False)
    qty = Column(Integer, nullable=False)
    value = Column(Float, nullable=False)
    # Charge breakdown
    brokerage = Column(Float, default=0.0)
    stt = Column(Float, default=0.0)
    exc_charges = Column(Float, default=0.0)
    gst = Column(Float, default=0.0)
    sebi_charges = Column(Float, default=0.0)
    stamp_duty = Column(Float, default=0.0)
    total_charges = Column(Float, default=0.0)
    # Realistic mode
    charges_source = Column(String, default="calculated")  # "calculated" or "api"
    timestamp = Column(DateTime, default=datetime.utcnow)


class LivePnLSnapshotDB(Base):
    """Periodic PnL snapshots for live deployments."""
    __tablename__ = "live_pnl_snapshots"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    deployment_id = Column(String, nullable=False, index=True)
    strategy_id = Column(String, nullable=False, index=True)
    cash = Column(Float, nullable=False)
    equity = Column(Float, nullable=False)
    unrealized_pnl = Column(Float, default=0.0)
    realized_pnl = Column(Float, default=0.0)
    total_fees = Column(Float, default=0.0)
    total_pnl = Column(Float, default=0.0)
    margin_used = Column(Float, default=0.0)
    margin_free = Column(Float, default=0.0)
    position_count = Column(Integer, default=0)
    total_qty = Column(Integer, default=0)
    # JSON snapshot of all positions at this time
    positions_json = Column(Text, nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow)


class DeploymentEventDB(Base):
    """Logs deployment lifecycle events (start, stop, error, signal)."""
    __tablename__ = "deployment_events"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    deployment_id = Column(String, nullable=False, index=True)
    event_type = Column(String, nullable=False)  # "start", "stop", "tick", "order", "fill", "error", "margin_call"
    message = Column(Text, nullable=True)
    data_json = Column(Text, nullable=True)  # Extra structured data
    timestamp = Column(DateTime, default=datetime.utcnow)


class BacktestResultDB(Base):
    """Stores backtest run results and metadata."""
    __tablename__ = "backtest_results"

    id = Column(String, primary_key=True)
    strategy_id = Column(String, nullable=True)
    strategy_name = Column(String, nullable=False)
    symbol = Column(String, nullable=False)  # Primary symbol for display
    symbols_json = Column(Text, nullable=True)  # JSON: all symbols used
    interval = Column(String, nullable=False)
    start_time = Column(String, nullable=False)
    end_time = Column(String, nullable=False)

    initial_capital = Column(Float, nullable=False)
    final_equity = Column(Float, nullable=False)
    total_pnl = Column(Float, nullable=False)

    cagr = Column(Float, nullable=False)
    sharpe_ratio = Column(Float, nullable=False)
    sortino_ratio = Column(Float, nullable=False)
    max_drawdown = Column(Float, nullable=False)
    win_rate = Column(Float, nullable=False)
    profit_factor = Column(Float, nullable=False)
    total_fees = Column(Float, nullable=False)
    max_position_size = Column(Integer, nullable=True)

    log_file_path = Column(String, nullable=False)  # Path to JSONL replay events
    metrics_json = Column(Text, nullable=False)  # JSON: detailed metrics, trades, cost breakdown

    created_at = Column(DateTime, default=datetime.utcnow)


def init_db():
    """Initialize database tables and perform migrations."""
    Base.metadata.create_all(bind=engine)

    # Migration helpers
    def add_column(table, col_name, col_def):
        try:
            with engine.connect() as conn:
                conn.execute(text(f'ALTER TABLE {table} ADD COLUMN {col_name} {col_def}'))
                conn.commit()
                print(f"INFO: Database migration: Added '{col_name}' to {table}.")
        except Exception:
            pass  # Column likely exists

    # backtest_results migrations
    add_column("backtest_results", "max_position_size", "INTEGER")
    add_column("backtest_results", "symbols_json", "TEXT")

    # strategies migrations
    add_column("strategies", "runtime_type", 'TEXT DEFAULT "legacy_on_bar"')
    add_column("strategies", "entrypoint", "TEXT")
    add_column("strategies", "symbols", 'TEXT DEFAULT \'["SBIN"]\'')
    add_column("strategies", "interval", 'TEXT DEFAULT "FIVE_MINUTE"')
    add_column("strategies", "initial_capital", "REAL DEFAULT 100000.0")
    add_column("strategies", "max_position_size", "INTEGER")
    add_column("strategies", "parameters_json", "TEXT")
    add_column("strategies", "risk_settings_json", "TEXT")

    # deployments table is created by Base.metadata.create_all above


def get_db() -> Generator[Session, None, None]:
    """Dependency for FastAPI to inject database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
